# Generated by Django 2.2.5 on 2019-09-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('due_date', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Najważeniejszy'), (1, 'Prawie najważniejszy'), (2, 'Wysoki'), (3, 'Normalny'), (4, 'Niski')], default=3)),
                ('label_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.Label')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_todoitems', to='todolist.Project')),
            ],
        ),
    ]
