# Generated by Django 2.2.5 on 2019-09-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('todo_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
                ('due_date', models.DateTimeField()),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Label')),
            ],
        ),
    ]
