# Generated by Django 2.2.5 on 2019-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190912_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Najważeniejszy'), (1, 'Prawie najważniejszy'), (2, 'Wysoki'), (3, 'Normalny'), (4, 'Niski')], default=3),
        ),
    ]
