# Generated by Django 2.2.5 on 2019-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190921_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='period_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='period_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
