# Generated by Django 2.2.5 on 2019-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190923_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='due_time',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
