# Generated by Django 2.2.5 on 2019-09-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190923_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='period_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Co godzinę'), (2, 'Co dzień'), (3, 'Co tydzień'), (4, 'Co miesiąc'), (5, 'Co rok')], default=0),
        ),
    ]
